spring.application.name=bandhub

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5433/bandhub
spring.datasource.username=postgres
spring.datasource.password=1234

# Hibernate mira tus entidades Java 
# y actualiza las tablas automáticamente en desarrollo
spring.jpa.hibernate.ddl-auto=update
# muestra en consola las consultas SQL generadas.
spring.jpa.show-sql=true
# Hace sque el sql salga mas legible
spring.jpa.properties.hibernate.format_sql=true